/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PdfRouteImport } from './routes/pdf'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSigninRouteImport } from './routes/api/signin'

const PdfRoute = PdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSigninRoute = ApiSigninRouteImport.update({
  id: '/api/signin',
  path: '/api/signin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pdf': typeof PdfRoute
  '/api/signin': typeof ApiSigninRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pdf': typeof PdfRoute
  '/api/signin': typeof ApiSigninRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pdf': typeof PdfRoute
  '/api/signin': typeof ApiSigninRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pdf' | '/api/signin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pdf' | '/api/signin'
  id: '__root__' | '/' | '/pdf' | '/api/signin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PdfRoute: typeof PdfRoute
  ApiSigninRoute: typeof ApiSigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pdf': {
      id: '/pdf'
      path: '/pdf'
      fullPath: '/pdf'
      preLoaderRoute: typeof PdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signin': {
      id: '/api/signin'
      path: '/api/signin'
      fullPath: '/api/signin'
      preLoaderRoute: typeof ApiSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PdfRoute: PdfRoute,
  ApiSigninRoute: ApiSigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
